version: '3'

services:
  rift:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - ./uploads:/app/rift/uploads
  mongo:
    image: mongo
    volumes:
      - ./mongo_data:/data/db
    ports:
      - "27017:27017"